### ISSUE TITLE
PromiseKit  - tests failing

### ISSUE THREAD

**Issue by tonikocjan** [poviolabs/PovioKit#183]
I tried running the tests repeatedly and couldn't get them to fail, none the less, I suggest that we add the delay only for `testAllResolvedOnMainThread()` as an initial workaround until this is fully resolved. If the other tests perform as expected we shouldn't burden them with the additional delay.

``` swift
  func testAllResolvedOnMainThread() {
    let ex1 = expectation(description: "")
    let ex2 = expectation(description: "")
    all(on: .main, promises: [async(0, delay: 0.05 ,on: .main), async(1, delay: 0.05, on: .main)])
      .then { _ in
        XCTAssertTrue(Thread.isMainThread)
        ex1.fulfill()
      }
    all(on: .main, promises: [async(0, on: .main), async(NSError.err, Int.self, delay: 0.05, on: .main)])
      .catch { _ in
        XCTAssertTrue(Thread.isMainThread)
        ex2.fulfill()
      }
    waitForExpectations(timeout: 2)
  }
```

I did some further evaluation and for example `testAllListAsyncFailing` if we set the delay to 0. `func all<T, C>(on dispatchQueue: DispatchQueue? = .main, promises: C)` fails to stop on the first error promise. I don't want to hijack this PR with these discussions but I believe this needs evaluation since it's not performing as intended.

_Originally posted by @gentique in https://github.com/poviolabs/PovioKit/issues/139#issuecomment-1223620801_

**Comment by tonikocjan** [comment]
@gentique can you provide an example where `testAllListAsyncFailing` is failing.

**Comment by gentique** [comment]
Yes, so on `testAllListAsyncFailing` if we set the delay to 0.01 (as it is right now), the tests run and pass successfully.
<img width="656" alt="Screen Shot 2022-08-24 at 9 57 06 AM" src="https://user-images.githubusercontent.com/15278390/186364180-684434f0-2197-4656-9178-6d8e287ee1c7.png">
We can see that it goes only once on the catch clause and stops the remaining calls.

But if we change the delay and set it to 0, it sometimes fails.
<img width="656" alt="Screen Shot 2022-08-24 at 9 59 52 AM" src="https://user-images.githubusercontent.com/15278390/186364341-eee73e1f-0bea-4868-9e50-1ca3b7ce0dfe.png">

I run the tests repeatedly and sometimes they all pass, but a lot of the times they don't.

<img width="497" alt="Screen Shot 2022-08-24 at 10 00 14 AM" src="https://user-images.githubusercontent.com/15278390/186364425-ea6542f4-be68-45fd-864e-9a33bf97d43e.png">

I ran these tests on the current develop branch, using Xcode 13.4.1 on iPhone 13 pro (15.5) simulator

**Comment by tonikocjan** [comment]
@gentique Thanks. Can you try it again from [this branch](https://github.com/poviolabs/PovioKit/tree/promise/fix-observers-dispatch)? Should be fixed.

**Comment by gentique** [comment]
> @gentique Thanks. Can you try it again from [this branch](https://github.com/poviolabs/PovioKit/tree/promise/fix-observers-dispatch)? Should be fixed.

Just tested it out, looks good!

**Comment by tonikocjan** [comment]
#184
